image: microsoft/dotnet/core/sdk:3.1

stages:
    - build
    # - test

variables:
    test: "Example.Test"

before_script:
    - "cd BudBudget.REST"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
# test:
#     stage: test
#     script:
#         - "cd $test"
#         - "dotnet test"
